// сохранённый запрос
const recipesDef = [
  {
    id: 651225,
    title: 'Mashed Potatoes with Garlic, Sage & Goat Cheese',
    image: 'https://spoonacular.com/recipeImages/651225-312x231.jpg',
    imageType: 'jpg',
    usedIngredientCount: 2,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 11215,
        amount: 1,
        unit: 'tsp',
        unitLong: 'teaspoon',
        unitShort: 'tsp',
        aisle: 'Produce',
        name: 'garlic',
        original: '1 tsp. garlic ( minced)',
        originalName: 'garlic ( minced)',
        meta: [Array],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/garlic.png',
      },
      {
        id: 99226,
        amount: 14,
        unit: 'tsp',
        unitLong: 'teaspoons',
        unitShort: 'tsp',
        aisle: 'Produce',
        name: 'sage',
        original: '1 /4 tsp sage',
        originalName: 'sage',
        meta: [],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/fresh-sage.png',
      },
    ],
    usedIngredients: [
      {
        id: 11353,
        amount: 3,
        unit: 'medium size',
        unitLong: 'medium sizes',
        unitShort: 'medium size',
        aisle: 'Produce',
        name: 'baking potatoes',
        original: '3 ea. medium size baking potatoes (peeled and cut in 1 inch pieces)',
        originalName: 'ea. medium size baking potatoes (peeled and cut in 1 inch pieces)',
        meta: [Array],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/russet-or-idaho-potatoes.png',
      },
      {
        id: 1159,
        amount: 5.3,
        unit: 'oz',
        unitLong: 'ounces',
        unitShort: 'oz',
        aisle: 'Cheese',
        name: 'goat cheese',
        original: '1 (5.3 oz.) Chavrie Goat Cheese Pyramid, Original',
        originalName: 'Chavrie Goat Cheese Pyramid, Original',
        meta: [],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/goat-cheese.jpg',
      },
    ],
    unusedIngredients: [
      {
        id: 5006,
        amount: 1,
        unit: 'serving',
        unitLong: 'serving',
        unitShort: 'serving',
        aisle: 'Meat',
        name: 'chicken',
        original: 'chicken',
        originalName: 'chicken',
        meta: [],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/whole-chicken.jpg',
      },
      {
        id: 11529,
        amount: 1,
        unit: 'serving',
        unitLong: 'serving',
        unitShort: 'serving',
        aisle: 'Produce',
        name: 'tomato',
        original: 'tomato',
        originalName: 'tomato',
        meta: [],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/tomato.png',
      },
    ],
    likes: 2,
  },
  {
    id: 643633,
    title: 'Fresh Tomato Mozzarella Side Salad',
    image: 'https://spoonacular.com/recipeImages/643633-312x231.jpg',
    imageType: 'jpg',
    usedIngredientCount: 2,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 2069,
        amount: 0.25,
        unit: 'cup',
        unitLong: 'cups',
        unitShort: 'cup',
        aisle: 'Oil, Vinegar, Salad Dressing',
        name: 'balsamic vinegar',
        original: '1/4 cup Balsamic vinegar',
        originalName: 'Balsamic vinegar',
        meta: [],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/balsamic-vinegar.jpg',
      },
      {
        id: 2044,
        amount: 4,
        unit: '',
        unitLong: '',
        unitShort: '',
        aisle: 'Produce',
        name: 'basil leaves',
        original: '4 Fresh basil leaves, finely chopped or shredded',
        originalName: 'Fresh basil leaves, finely chopped or shredded',
        meta: [Array],
        extendedName: 'shredded fresh basil leaves',
        image: 'https://spoonacular.com/cdn/ingredients_100x100/fresh-basil.jpg',
      },
    ],
    usedIngredients: [
      {
        id: 1026,
        amount: 16,
        unit: 'oz',
        unitLong: 'ounces',
        unitShort: 'oz',
        aisle: 'Cheese',
        name: 'mozzarella',
        original: 'Bel Gioioso Fresh Mozzarella (about 16 oz.)',
        originalName: 'Bel Gioioso Fresh Mozzarella (about',
        meta: [Array],
        extendedName: 'fresh mozzarella',
        image: 'https://spoonacular.com/cdn/ingredients_100x100/mozzarella.png',
      },
      {
        id: 10211529,
        amount: 4,
        unit: '',
        unitLong: '',
        unitShort: '',
        aisle: 'Produce',
        name: 'roma tomatoes',
        original: '4 Vine ripened tomatoes OR 4-6 Roma tomatoes',
        originalName: 'Vine ripened tomatoes OR 4-6 Roma tomatoes',
        meta: [],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/roma-tomatoes.png',
      },
    ],
    unusedIngredients: [
      {
        id: 5006,
        amount: 1,
        unit: 'serving',
        unitLong: 'serving',
        unitShort: 'serving',
        aisle: 'Meat',
        name: 'chicken',
        original: 'chicken',
        originalName: 'chicken',
        meta: [],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/whole-chicken.jpg',
      },
      {
        id: 11352,
        amount: 1,
        unit: 'serving',
        unitLong: 'serving',
        unitShort: 'serving',
        aisle: 'Produce',
        name: 'potato',
        original: 'potato',
        originalName: 'potato',
        meta: [],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/potatoes-yukon-gold.png',
      },
    ],
    likes: 2,
  },
  {
    id: 648368,
    title: 'Jalapeno Queso With Goat Cheese',
    image: 'https://spoonacular.com/recipeImages/648368-312x231.jpg',
    imageType: 'jpg',
    usedIngredientCount: 2,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 11979,
        amount: 1,
        unit: '',
        unitLong: '',
        unitShort: '',
        aisle: 'Canned and Jarred;Produce;Ethnic Foods',
        name: 'jalapeno pepper',
        original: '1 ea. jalapeno pepper diced',
        originalName: 'ea. jalapeno pepper diced',
        meta: [Array],
        extendedName: 'diced jalapeno pepper',
        image: 'https://spoonacular.com/cdn/ingredients_100x100/jalapeno-pepper.png',
      },
      {
        id: 6168,
        amount: 2,
        unit: 'teaspoons',
        unitLong: 'teaspoons',
        unitShort: 'tsp',
        aisle: 'Condiments',
        name: 'hot sauce',
        original: '2 teaspoons hot sauce',
        originalName: 'hot sauce',
        meta: [],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/hot-sauce-or-tabasco.png',
      },
    ],
    usedIngredients: [
      {
        id: 1159,
        amount: 5.3,
        unit: 'oz',
        unitLong: 'ounces',
        unitShort: 'oz',
        aisle: 'Cheese',
        name: 'goat cheese',
        original: '1 package (5.3 oz) Fresh Goat Cheese, such as Chavrie',
        originalName: 'package Fresh Goat Cheese, such as Chavrie',
        meta: [Array],
        extendedName: 'fresh goat cheese',
        image: 'https://spoonacular.com/cdn/ingredients_100x100/goat-cheese.jpg',
      },
      {
        id: 10011693,
        amount: 8,
        unit: 'oz',
        unitLong: 'ounces',
        unitShort: 'oz',
        aisle: 'Canned and Jarred',
        name: 'canned tomatoes',
        original: '8 oz. can diced tomatoes, drained',
        originalName: 'diced tomatoes, drained',
        meta: [Array],
        extendedName: 'diced canned tomatoes',
        image: 'https://spoonacular.com/cdn/ingredients_100x100/tomatoes-canned.png',
      },
    ],
    unusedIngredients: [
      {
        id: 5006,
        amount: 1,
        unit: 'serving',
        unitLong: 'serving',
        unitShort: 'serving',
        aisle: 'Meat',
        name: 'chicken',
        original: 'chicken',
        originalName: 'chicken',
        meta: [],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/whole-chicken.jpg',
      },
      {
        id: 11352,
        amount: 1,
        unit: 'serving',
        unitLong: 'serving',
        unitShort: 'serving',
        aisle: 'Produce',
        name: 'potato',
        original: 'potato',
        originalName: 'potato',
        meta: [],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/potatoes-yukon-gold.png',
      },
    ],
    likes: 1,
  },
  {
    id: 644953,
    title: 'Goat Cheese Pesto Pizza',
    image: 'https://spoonacular.com/recipeImages/644953-312x231.jpg',
    imageType: 'jpg',
    usedIngredientCount: 2,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 93770,
        amount: 1,
        unit: '',
        unitLong: '',
        unitShort: '',
        aisle: 'Pasta and Rice;Refrigerated',
        name: 'pizza shell',
        original: '1 prepared pizza shell, 14 inches',
        originalName: 'prepared pizza shell, 14 inches',
        meta: [Array],
        extendedName: 'cooked pizza shell',
        image: 'https://spoonacular.com/cdn/ingredients_100x100/pizza-dough.jpg',
      },
      {
        id: 93698,
        amount: 1,
        unit: 'cup',
        unitLong: 'cup',
        unitShort: 'cup',
        aisle: 'Pasta and Rice',
        name: 'pesto',
        original: '1 cup pesto',
        originalName: 'pesto',
        meta: [],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/basil-pesto.png',
      },
    ],
    usedIngredients: [
      {
        id: 11529,
        amount: 1,
        unit: 'cup',
        unitLong: 'cup',
        unitShort: 'cup',
        aisle: 'Produce',
        name: 'tomatoes',
        original: '1 cup diced Tomatoes',
        originalName: 'diced Tomatoes',
        meta: [Array],
        extendedName: 'diced tomatoes',
        image: 'https://spoonacular.com/cdn/ingredients_100x100/tomato.png',
      },
      {
        id: 1159,
        amount: 1,
        unit: 'package',
        unitLong: 'package',
        unitShort: 'pkg',
        aisle: 'Cheese',
        name: 'goat cheese',
        original: '1 package of crumbled goat cheese, Alouette Provencal variety',
        originalName: 'crumbled goat cheese, Alouette Provencal variety',
        meta: [Array],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/goat-cheese.jpg',
      },
    ],
    unusedIngredients: [
      {
        id: 5006,
        amount: 1,
        unit: 'serving',
        unitLong: 'serving',
        unitShort: 'serving',
        aisle: 'Meat',
        name: 'chicken',
        original: 'chicken',
        originalName: 'chicken',
        meta: [],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/whole-chicken.jpg',
      },
      {
        id: 11352,
        amount: 1,
        unit: 'serving',
        unitLong: 'serving',
        unitShort: 'serving',
        aisle: 'Produce',
        name: 'potato',
        original: 'potato',
        originalName: 'potato',
        meta: [],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/potatoes-yukon-gold.png',
      },
    ],
    likes: 1,
  },
  {
    id: 633852,
    title: 'baked tomatoes',
    image: 'https://spoonacular.com/recipeImages/633852-312x231.jpg',
    imageType: 'jpg',
    usedIngredientCount: 2,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 1106,
        amount: 0.25,
        unit: 'cup',
        unitLong: 'cups',
        unitShort: 'cup',
        aisle: 'Milk, Eggs, Other Dairy',
        name: 'goat milk',
        original: "1/4 cup of soft, unripened goat's milk cheese",
        originalName: "soft, unripened goat's milk cheese",
        meta: [Array],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/milk.png',
      },
      {
        id: 2044,
        amount: 1,
        unit: 'tbsp',
        unitLong: 'tablespoon',
        unitShort: 'Tbsp',
        aisle: 'Produce',
        name: 'basil',
        original: '1 tbsp chopped basil',
        originalName: 'chopped basil',
        meta: [Array],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/fresh-basil.jpg',
      },
    ],
    usedIngredients: [
      {
        id: 11529,
        amount: 2,
        unit: '',
        unitLong: '',
        unitShort: '',
        aisle: 'Produce',
        name: 'tomatoes',
        original: '2 tomatoes (I used hothouse but any reasonable sized tomato would do the trick)',
        originalName: 'tomatoes (I used hothouse but any reasonable sized tomato would do the trick)',
        meta: [Array],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/tomato.png',
      },
      {
        id: 1033,
        amount: 2,
        unit: 'tbsp',
        unitLong: 'tablespoons',
        unitShort: 'Tbsp',
        aisle: 'Cheese',
        name: 'parmesan',
        original: '2 tbsp grated parmesan',
        originalName: 'grated parmesan',
        meta: [Array],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/parmesan.jpg',
      },
    ],
    unusedIngredients: [
      {
        id: 5006,
        amount: 1,
        unit: 'serving',
        unitLong: 'serving',
        unitShort: 'serving',
        aisle: 'Meat',
        name: 'chicken',
        original: 'chicken',
        originalName: 'chicken',
        meta: [],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/whole-chicken.jpg',
      },
      {
        id: 11352,
        amount: 1,
        unit: 'serving',
        unitLong: 'serving',
        unitShort: 'serving',
        aisle: 'Produce',
        name: 'potato',
        original: 'potato',
        originalName: 'potato',
        meta: [],
        image: 'https://spoonacular.com/cdn/ingredients_100x100/potatoes-yukon-gold.png',
      },
    ],
    likes: 1,
  },
];

const recipe = {

  id: 640457,
  title: 'Crash Hot Potatoes',
  timeOfCook: 45,
  servings: 4,
  image: 'https://spoonacular.com/recipeImages/640457-556x370.jpg',
  instructions: 'Preheat oven to 450 F. Place a sheet of parchment paper on a cookie sheet. Wash the potatoes until they are clean. Put the potatoes in a pot and fill with water. Add about 2 tablespoons of salt to the water. Place the water on a medium high flame and bring to a boil. Boil them until they are tender all the way through. Make sure a fork pierces them easily. Drain the potatoes. Let the potatoes cool a little. Drizzle the cookie sheet with olive oil. Place the cooked potatoes on cookie sheet.\n'
    + '\n'
    + "Using a small paring knife, make an X cut on the top of each potato so it's easier to crush them. Use a potato masher and gently press on each potato until squashed but not disintegrated. You want them to stay together. If they fall apart, don't worry! Just pick up the bits into piles and keep going.\n"
    + '\n'
    + "Once smashed, generously sprinkle kosher salt over each potato. Follow with pepper, and then, drizzle them with more olive oil. If desired, sprinkle each potato with freshly chopped rosemary or chives if desired. Sprinkle with smoked paprika to finish them off if desired. Bake the potatoes at 450 F for 20-25 minutes, longer is better, you want them very crisp, just don't let them burn. Serve hot!",
  //   analyzedInstructions: recipeDef.analyzedInstructions,
  // calories: Math.round(el.calories),
  fav: false,
};
